config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('', include('pages.urls',namespace='pages')),
    path('listings/', include('listings.urls',namespace='listings')),
    path('admin/', admin.site.urls),
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 


admin.site.site_header = "Clinic Administration"
admin.site.site_title = "Clinic Admin Portal"
admin.site.index_title = "Welcome to Clinic Portal"

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.listings, name='index'),
    path('<int:listing_id>/', views.listing, name='listing'),
    path('search/', views.search, name='search'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about')
]

doctors/models.py
from django.db import models

# Create your models here.
class Doctor(models.Model):
    name= models.CharField(max_length=200)
    photo=models.ImageField(upload_to='photos/%Y/%m/%d/')
    description = models.TextField(blank=True)
    phone = models.CharField(max_length=20, blank='00000000')
    email = models.EmailField(max_length=50,unique=True,blank=False)
    is_mvp = models.BooleanField(default=True)
    hire_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

listings/models.py
from django.db import models
from doctors.models import Doctor
# Create your models here.
class Listing(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    district = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    services = models.TextField(blank=True)
    service = models.IntegerField()
    room_type = models.CharField(max_length=200, default='')
    rooms = models.CharField(max_length=2)
    professions = models.CharField(max_length=200, default='')
    photo_main = models.ImageField(upload_to='photo/%Y/%m/%d')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-list_date']
        indexes = [models.Index(fields=['list_date'])]
    def __str__(self):
        return self.title

pages/models.py
from django.db import models

# Create your models here.

doctors/views.py
from django.shortcuts import render

# Create your views here.

listings/views.py
from django.shortcuts import render, get_object_or_404
from .models import Listing
from django.core.paginator import Paginator
from .choices import district_choices, rooms_choices, room_choices
from django.db.models import Q
# Create your views here.
def listings(request):
    listings = Listing.objects.filter(is_published=True)
    paginator = Paginator(listings,3)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)
    context = {"listings" : paged_listings}
    return render(request, 'listings/listings.html', context)

def listing(request,listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    context = {"listing": listing}
    return render(request, 'listings/listing.html', context)

def search(request):
    queryset_list = Listing.objects.order_by('-list_date')
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_lsit = queryset_list.filter(Q(description__icontains=keywords)| Q(title__icontains=keywords)| Q(doctor__name__icontains=keywords))
    if 'district' in request.GET:
        district = request.GET['district']
        if district:
            queryset_list =queryset_list.filter(district__iexact=district)
    if 'rooms' in request.GET:
        rooms = request.GET['rooms']
        if rooms:
            queryset_list =queryset_list.filter(rooms__gte=rooms)
    if 'room_type' in request.GET:
        room_type = request.GET['room_type']
        if room_type:
            queryset_list = queryset_list.filter(room_type__iexact=room_type)
    paginator = Paginator(queryset_list,3)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)
    context = {
        "listings": queryset_list,
        'district_choices': district_choices,
        'rooms_choices': rooms_choices,
        'room_choices': room_choices,
        'values': request.GET
        }
    return render(request, 'listings/search.html',context)

pages/views.py
from django.shortcuts import render
from listings.models import Listing
from doctors.models import Doctor
from listings.choices import district_choices, room_choices, rooms_choices
# ! Create your views here.

def index(request):
    listings = Listing.objects.order_by('-list_date').filter(is_published=True)[:3]
    context = {"listings": listings,
               "district_choices": district_choices,
               "room_choices": room_choices,
               "rooms_choices": rooms_choices,
               }
    return render(request,'pages/index.html', context)

def about(request):
    doctors = Doctor.objects.order_by("-hire_date")[:3]
    mvp_doctors = Doctor.objects.all().filter(is_mvp=True)
    print(mvp_doctors)
    context = {"doctors": doctors, "mvp_doctors": mvp_doctors}
    return render(request, 'pages/about.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href={% static "css/all.css" %} />
    <!-- Bootstrap -->
    <link rel="stylesheet" href={% static "css/bootstrap.css" %} />
    <!-- Lightbox -->
    <link rel="stylesheet" href={% static "css/lightbox.min.css" %} />
    <!-- Custom -->
    <link rel="stylesheet" href={% static "css/style.css" %} />

    <title>BC Health Care</title>
  </head>
  <body>
    <!-- topbar -->
    {% include 'partials/_topbar.html' %}
    <!-- navbar -->
    {% include 'partials/_navbar.html' %}
    <!-- content -->
    {% block content %}{% endblock %}
    <!-- footer -->
    {% include 'partials/_footer.html' %}
    <script src={% static "js/jquery-3.3.1.min.js"  %}></script>
    <script src={% static "js/bootstrap.bundle.min.js" %}></script>
    <script src={% static "js/lightbox.min.js" %}></script>
    <script src={% static "js/main.js" %}></script>
  </body>
</html>

templates/listings/listing.html
{% extends "base.html" %}
<!-- load static-->
{% load static %}
<!-- loads humanize-->
{% load humanize %} {% block content %}
<section id="showcase-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">{{listing.title | title}}</h1>
        <p class="lead">
          <i class="fas fa-map-marker"></i> {{listing.district | title}}
        </p>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'pages:index' %}">Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'listings:index' %}">Listings</a>
        </li>
        <li class="breadcrumb-item active">{{listing.title | title}}</li>
      </ol>
    </nav>
  </div>
</section>

<!-- Listing -->
<section id="listing" class="py-4">
  <div class="container">
    <a href="{% url 'listings:index' %}" class="btn btn-light mb-4"
      >Back To Listings</a
    >
    <div class="row">
      <div class="col-md-9">
        <!-- Home Main Image -->
        <img
          src="{{listing.photo_main.url}}"
          alt=""
          class="img-main img-fluid mb-3"
        />
        <!-- Thumbnails -->
        <div class="row mb-5 thumbs">
          <div class="col-md-3">
            {% if listing.photo_1 %}
            <a href="{{listing.photo_1.url}}" data-lightbox="home-images">
              <img src="{{listing.photo_1.url}}" alt="" class="img-fluid" />
            </a>
            {% endif %}
          </div>
          <div class="col-md-3">
            {% if listing.photo_2 %}
            <a href="{{listing.photo_2.url}}" data-lightbox="home-images">
              <img src="{{listing.photo_2.url}}" alt="" class="img-fluid" />
            </a>
            {% endif %}
          </div>
          <div class="col-md-3">
            {% if listing.photo_3 %}
            <a href="{{listing.photo_3.url}}" data-lightbox="home-images">
              <img src="{{listing.photo_3.url}}" alt="" class="img-fluid" />
            </a>
            {% endif %}
          </div>
          <div class="col-md-3">
            {% if listing.photo_4 %}
            <a href="{{listing.photo_4.url}}" data-lightbox="home-images">
              <img src="{{listing.photo_4.url}}" alt="" class="img-fluid" />
            </a>
            {% endif %}
          </div>
        </div>
        <!-- Fields -->
        <div class="row mb-5 fields">
          <div class="col-md-6">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-secondary">
                <i class="fas fa-money-bill-alt"></i> {{listing.title | title}}
                Fee Estimate:
                <span class="float-right">$20,000/Day</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-bed"></i> rooms:
                <span class="float-right">{{listing.rooms}}</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-bath"></i> Room type:
                <span class="float-right">{{listing.room_type}}</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-dumbbell"></i> Treatment:
                <span class="float-right"> Have </span>
              </li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-secondary">
                <i class="fas fa-th-large"></i> Restrooms:
                <span class="float-right">Have</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-square"></i> Specialized Care:
                <span class="float-right">No</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-calendar"></i> Preventative Services:
                <span class="float-right">Have</span>
              </li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-bed"></i> Minor Surgical Procedures:
                <span class="float-right">No</span>
              </li>
            </ul>
          </div>
        </div>

        <!-- Description -->
        <div class="row mb-5">
          <div class="col-md-12">{{listing.description | linebreaks}}</div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card mb-3">
          <img
            class="card-img-top"
            src="{{listing.doctor.photo.url}}"
            alt="Doctor of the month"
          />
          <div class="card-body">
            <h5 class="card-title">Medical Practitioner</h5>
            <h6 class="text-secondary">{{listing.doctor.name}}</h6>
          </div>
        </div>
        <button
          class="btn-primary btn-block btn-lg"
          data-toggle="modal"
          data-target="#inquiryModal"
        >
          Make An Inquiry
        </button>
      </div>
    </div>
  </div>
</section>

<!-- Inquiry Modal -->
<div class="modal fade" id="inquiryModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="property_name" class="col-form-label">Property:</label>
            <input
              type="text"
              name="listing"
              class="form-control"
              value="45 Prince Street"
              disabled
            />
          </div>
          <div class="form-group">
            <label for="name" class="col-form-label">Name:</label>
            <input type="text" name="name" class="form-control" required />
          </div>
          <div class="form-group">
            <label for="email" class="col-form-label">Email:</label>
            <input type="email" name="email" class="form-control" required />
          </div>
          <div class="form-group">
            <label for="phone" class="col-form-label">Phone:</label>
            <input type="text" name="phone" class="form-control" />
          </div>
          <div class="form-group">
            <label for="message" class="col-form-label">Message:</label>
            <textarea name="message" class="form-control"></textarea>
          </div>
          <hr />
          <input
            type="submit"
            value="Send"
            class="btn btn-block btn-secondary"
          />
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/listings/listings.html
{% extends "base.html" %}
<!--load base-->
{% load static %}
<!--load static -->
{% load humanize %}
<!-- humanize -->
{% block content %}
<section id="showcase-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">Browse Our Clinic</h1>
        <p class="lead">
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
          pariatur!
        </p>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'pages:index' %}">
            <i class="fas fa-home"></i> Home</a
          >
        </li>
        <li class="breadcrumb-item active">Browse Listings</li>
      </ol>
    </nav>
  </div>
</section>

<!-- Listings -->
<section id="listings" class="py-4">
  <div class="container">
    <div class="row">
      {% if listings %}
      <!-- Listing 1 -->
      {% for listing in listings %}
      <div class="col-md-6 col-lg-4 mb-4">
        <div class="card listing-preview">
          <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="" />
          <div class="card-img-overlay"></div>
          <div class="card-body">
            <div class="listing-heading text-center">
              <h4 class="text-primary">{{ listing.title | title }}</h4>
              <p>
                <i class="fas fa-map-marker text-secondary"></i>
                {{listing.district | title}}
              </p>
            </div>
            <hr />
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-th-large"></i>
                Services {{listing.service|apnumber | capfirst}}
              </div>
              <div class="col-6"><i class="fas fa-dumbbell"></i> Treatment</div>
            </div>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-bed"></i> rooms {{listing.rooms}}
              </div>
              <div class="col-6"><i class="fas fa-bath"></i> Bathrooms</div>
            </div>
            <hr />
            <div class="row py-2 text-secondary">
              <div class="col-12">
                <i class="fas fa-user"></i> {{listing.doctor.name}}
              </div>
            </div>
            <div class="row text-secondary pb-2">
              <div class="col-12">
                <i class="fas fa-clock"></i> {{listing.list_date | timesince}}
              </div>
            </div>
            <hr />
            {% comment %} listing {% endcomment %}
            <a
              href="{% url 'listings:listing' listing.id %}"
              class="btn btn-primary btn-block"
              >More Info</a
            >
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <div class="col-md-12">
        <h2>No Clinic Available</h2>
      </div>
      {% endif %}
    </div>
    <div class="row">
      <div class="col-md-12">
        {% if listings.has_other_pages %}
        <ul class="pagination">
          {% if listings.has_previous %}
          <li class="page-item">
            <a
              class="page-link"
              href="?page={{ listings.previous_page_number }}"
              >&laquo;</a
            >
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">&laquo;</a>
          </li>
          {% endif %}
          <!--for loop page number-->
          {% for i in listings.paginator.page_range %}
          <!--page number-->
          {% if listings.number == i %}
          <li class="page-item active">
            <a class="page-link">{{ i }}</a>
          </li>
          {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
          {% endif %} {% endfor %}
          
          {% if listings.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ listings.next_page_number }}"
              >&raquo;</a
            >
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">&raquo;</a>
          </li>
          {% endif %}
        </ul>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}
<!--load humanize-->
{% load humanize %}
<!-- about main content-->
{% block content %}
<section id="showcase-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">About BC Health Care</h1>
        <p class="lead">
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
          pariatur!
        </p>
      </div>
    </div>
  </div>
</section>

<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href={% url 'pages:index' %}> <i class="fas fa-home"></i> Home</a>
        </li>
        <li class="breadcrumb-item active">About</li>
      </ol>
    </nav>
  </div>
</section>

<section id="about" class="py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h2>
          We Search For The Your health, your home – we help you find the right
          clinic.
        </h2>
        <p class="lead">
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
          pariatur!
        </p>

        <img src={% static 'img/about.jpg' %} alt="" />
        <p class="mt-4">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
          esse officia repudiandae ad saepe ex, amet neque quod accusamus rem
          quia magnam magni dolorum facilis ullam minima perferendis?
          Exercitationem at quaerat commodi id libero eveniet harum perferendis
          laborum molestias quia.
        </p>
      </div>
      <div class="col-md-4">
        {% if mvp_doctors %}
        {% for mvp_doctor in mvp_doctors %}
        <div class="card">
          <img
            class="card-img-top"
            src="{{mvp_doctor.photo.url}}"
            alt="Top Doctor of the month"
          />
          <div class="card-body">
            <h5 class="card-title">{{ forloop.counter | ordinal }} Top Doctor</h5>
            <h6 class="text-secondary">{{ mvp_doctor.name }}</h6>
            <p class="card-text">
             {{ mvp_doctor.description }}
            </p>
          </div>
        </div>
        {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
</section>

<section id="work" class="bg-dark text-white text-center">
  <h2 class="display-4">We Work For You</h2>
  <h4>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem velit
    aperiam, unde aliquid at similique!
  </h4>
  <hr />
  <a href="{% url 'listings:index' %}" class="btn btn-secondary text-white btn-lg"
    >View Our Featured Listings</a
  >
</section>

<!-- Team -->
{% if doctors %}
<section id="team" class="py-5">
  <div class="container">
    <h2 class="text-center pb-4">Our Team</h2>
    <div class="row text-center">
      {% for doctor in doctors %}
      <div class="col-md-4">
        <img
          src="{{ doctor.photo.url }}"
          alt=""
          class="rounded-circle mb-3 img-fluid"
          style="object-fit: cover; width: 300px; height: 300px"
        />
        <h4>{{ doctor.name }}</h4>
        <p class="text-success">
          <i class="fas fa-award text-success"></i> Doctor
        </p>
        <hr />
        <p><i class="fas fa-phone"></i> {{ doctor.phone }}</p>
        <p><i class="fas fa-envelope-open"></i> {{ doctor.email }}</p>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endif %}
{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}
<!-- load humanize-->
{% load humanize %}
<!--index main content-->
{% comment %} {% load static %} {% endcomment %}
{% block content %}
    <!--  Showcase  -->
    <section id="showcase">
      <div class="container text-center">
        <div class="home-search p-5">
          <div class="overlay p-5">
            
            <h1 class="display-4 mb-4">Clinic Searching Just Got So Easy</h1>
            
            <p class="lead">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit.
              Recusandae quas, asperiores eveniet vel nostrum magnam voluptatum
              tempore! Consectetur, id commodi!
            </p>
            <div class="search">
              <form action="{% url 'listings:search' %}" method="GET">
                <!--  Form Row 1  -->
                <div class="form-row">
                  <div class="col-md-12 mb-3">
                    <label class="sr-only">Keywords</label>
                    <input
                      type="text"
                      name="keywords"
                      class="form-control"
                      placeholder="Keyword (Clinic, Doctor, City name, Town name, etc)"
                    />
                  </div>
                </div>
                <!-- Form Row 2 -->
                <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <label class="sr-only">District</label>
                    <select name="district" class="form-control">
                      <option selected="true" disabled="disabled">
                        District (All)
                      </option>
                      {% for key,value in district_choices.items %}
                      <options value="{{ key }}">{{ value }}</options>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Rooms</label>
                    <select name="bedrooms" class="form-control">
                      <option selected="true" disabled="disabled">
                        Rooms (All)
                      </option>
                      {% for key,value in rooms_choices.items %}
                      <options value="{{ key }}">{{ value }}</options>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="col-md-4 mb-3">
                    <select name="price" class="form-control" id="type">
                      <option selected="true" disabled="disabled">
                        Room Types (All)
                      </option>
                      {% for key,value in room_choices.items %}
                      <options value="{{ key }}">{{ value }}</options>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <button class="btn btn-secondary btn-block mt-4" type="submit">
                  Submit form
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section id="listings" class="py-5">
      <div class="container">
        <h3 class="text-center mb-3">Inpatient medical services</h3>
        <div class="row">
          {% if listings %}
          <!-- Listings -->
          {% for listing in listings %}
          <!-- Listing 1 -->
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card listing-preview">
              <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="" />
              <div class="card-img-overlay"></div>
              <div class="card-body">
                <div class="listing-heading text-center">
                  <h4 class="text-primary">{{ listing.title | title }}</h4>
                  <p>
                    <i class="fas fa-map-marker text-secondary"></i> {{listing.district |title}}
                  </p>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-th-large"></i>
                    Services {{listing.service | apnumber | capfirst }}
                  </div>
                  <div class="col-6">
                    <i class="fas fa-dumbbell"></i> Treatment 
                  </div>
                </div>
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-bed"></i> {{listing.rooms}}
                  </div>
                  <div class="col-6">
                    <i class="fas fa-bath"></i> Bathrooms
                  </div>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-12"><i class="fas fa-user"></i>{{listing.doctor.name}}</div>
                </div>
                <div class="row text-secondary pb-2">
                  <div class="col-12">
                    <i class="fas fa-clock"></i> {{listing.list_date | timesince}}
                  </div>
                </div>
                <hr />
                {% comment %} listing {% endcomment %}
                <a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block"
                  >More Info</a
                >
              </div>
            </div>
          </div>
          {% endfor %} {% else%}
          <div class="col-md-12">
            <h2>No Clinic Available</h2>
          </div>
          {% endif %}
        </div>
      </div>
    </section>


    <section id="services" class="py-5 bg-secondary text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-4">
            <i class="fas fa-comment fa-4x mr-4"></i>
            <hr />
            <h3>Consulting Services</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt,
              debitis nam! Repudiandae, provident iste consequatur hic
              dignissimos ratione ea quae.
            </p>
          </div>
          <div class="col-md-4">
            <i class="fas fa-home fa-4x mr-4"></i>
            <hr />
            <h3>Inpatient Services</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt,
              debitis nam! Repudiandae, provident iste consequatur hic
              dignissimos ratione ea quae.
            </p>
          </div>
          <div class="col-md-4">
            <i class="fas fa-suitcase fa-4x mr-4"></i>
            <hr />
            <h3>Primary Care Package</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt,
              debitis nam! Repudiandae, provident iste consequatur hic
              dignissimos ratione ea quae.
            </p>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

templates/partials/_footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
  Copyright &copy;
  <span class="year"></span> BC Health Care 
</footer>

templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
      <div class="container">
        {% comment %} fix it later {% endcomment %}
        <a class="navbar-brand" href={% url 'pages:index' %}>
          <img src={% static "img/logo.png" %} class="logo" alt="" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavAltMarkup"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="navbar-nav">
            <li {% if '/' == request.path %} class="nav-item active mr-3" {% else %} class='nav-item mr-3' {% endif %}>
              {% comment %} fix index {% endcomment %}
              <a class="nav-link" href={% url 'pages:index' %}>Home</a>
            </li>
            <li {% if '/about' == request.path %} class="nav-item active mr-3" {% else %} class='nav-item mr-3' {% endif %}>
              {% comment %} fix about {% endcomment %}
              <a class="nav-link" href={% url 'pages:about' %}>About</a>
            </li>
            {% comment %} fix active css {% endcomment %}
            <li {% if '/listings/' == request.path %} class="nav-item active mr-3" {% else %} class='nav-item mr-3' {% endif %}class="nav-item mr-3">
              <a class="nav-link" href={% url 'listings:index' %}>Inpatient medical services</a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-3">
              {% comment %} fix register {% endcomment %}
              <a class="nav-link" href="register.html">
                <i class="fas fa-user-plus"></i> Register</a
              >
            </li>
            <li class="nav-item mr-3">
              {% comment %} fix login {% endcomment %}
              <a class="nav-link" href="login.html">
                <i class="fas fa-sign-in-alt"></i>

                Login</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>